const $=x=>document.getElementById(x);
const C={
front:[['弹簧刚度 N','fs',0,300,1,80],['预载 Turns','fp',0,25,.25,5],['LSC 低速压缩','flsc',0,50,1,10],['HSC 高速压缩','fhsc',0,8,.05,1.25],['LSR 低速回弹','flsr',0,50,1,10],['HSR 高速回弹','fhsr',0,8,.05,1],['K1 初段调节值','fk1',0,20,1,6],['K2 中后段调节值','fk2',0,20,1,8]],
rear:[['弹簧刚度 N','rs',0,300,1,150],['预载 mm','rp',0,60,.5,15],['LSC 低速压缩','rlsc',0,50,1,11],['HSC 高速压缩','rhsc',0,8,.05,1.5],['LSR 低速回弹','rlsr',0,60,1,14],['HSR 高速回弹','rhsr',0,8,.05,1],['K1 初段调节值','rk1',0,20,1,6],['K2 中后段调节值','rk2',0,20,1,8]]
};
function build(g){$(g+'Controls').innerHTML=C[g].map(a=>`<div><label>${a[0]}<output id="${a[1]}o">${a[5]}</output></label><input id="${a[1]}" type="range" min="${a[2]}" max="${a[3]}" step="${a[4]}" value="${a[5]}"></div>`).join('')}build('front');build('rear');
const M={trail:['Ninebot Enduro',200,260,26,108,'80/100-21','110/100-18'],scooter:['Ninebot Scooter',120,110,25,92,'120/70-12','130/70-12'],street:['Ninebot Performance',150,145,24.5,102,'110/70-17','150/60-17']};
function bike(m){let s='';if(m==='scooter')s='<circle class="wheel" cx="200" cy="275" r="60"/><circle class="wheel" cx="690" cy="275" r="60"/><path class="frame" d="M200 275L360 215L570 215L690 275M360 215L430 75L520 75M520 75L680 150L720 220"/><rect class="battery" x="390" y="160" width="210" height="55" rx="8"/><path class="hot" data-p="front" d="M410 105L250 250"/><path class="hot" data-p="rear" d="M600 180L650 250"/>';else if(m==='street')s='<circle class="wheel" cx="200" cy="280" r="70"/><circle class="wheel" cx="710" cy="280" r="70"/><path class="frame" d="M200 280L380 160L570 220L710 280M380 160L500 85L650 170"/><rect class="battery" x="470" y="145" width="150" height="75" rx="8"/><path class="hot" data-p="front" d="M390 125L230 260"/><path class="hot" data-p="rear" d="M590 175L650 260"/>';else s='<circle class="wheel" cx="190" cy="280" r="78"/><circle class="wheel" cx="700" cy="280" r="78"/><path class="frame" d="M190 280L360 145L550 210L700 280M360 145L480 85L610 180"/><rect class="battery" x="470" y="135" width="150" height="75" rx="8"/><path class="hot" data-p="front" d="M350 130L215 265"/><path class="hot" data-p="rear" d="M550 170L630 265"/>';
$('bike').innerHTML=s;$('hot').innerHTML='<circle class="dot" data-p="front" cx="310" cy="190" r="12"/><circle class="dot" data-p="rear" cx="620" cy="205" r="12"/>';document.querySelectorAll('[data-p]').forEach(x=>x.onclick=()=>go(x.dataset.p))}
function go(p){document.querySelectorAll('.page,nav button').forEach(x=>x.classList.remove('active'));$(p).classList.add('active');document.querySelector(`[data-p="${p}"]`)?.classList.add('active')}
document.querySelectorAll('nav button').forEach(x=>x.onclick=()=>go(x.dataset.p));
function model(m){let d=M[m];$('title').textContent=d[0];$('name').value=d[0];$('model').value=m;$('frontTravel').value=d[1];$('rearTravel').value=d[2];$('headAngle').value=d[3];$('trail').value=d[4];$('frontTire').value=d[5];$('rearTire').value=d[6];bike(m);calc()}
document.querySelectorAll('[data-model]').forEach(x=>x.onclick=()=>model(x.dataset.model));$('model').onchange=e=>model(e.target.value);
function n(id){return +$(id).value||0}
function calc(){C.front.concat(C.rear).forEach(a=>{if($(a[1]))$(a[1]+'o').textContent=$(a[1]).value});
let fp=(n('fl0')-n('fl2'))/Math.max(1,n('frontTravel'))*100,rp=(n('rl0')-n('rl2'))/Math.max(1,n('rearTravel'))*100,t=n('trail'),ang=n('headAngle'),score=Math.max(0,Math.min(100,100-Math.abs(fp-rp)*5-Math.abs(t-105)*.15));
$('fresult').textContent=`Rider SAG: ${fp.toFixed(1)}%`;$('rresult').textContent=`Rider SAG: ${rp.toFixed(1)}%`;
$('score').textContent=Math.round(score);$('status').textContent=Math.abs(fp-rp)<5?'平衡良好':'前后平衡偏差';$('advice').textContent=`前后 SAG ${fp.toFixed(1)}% / ${rp.toFixed(1)}%，前叉倾角 ${ang.toFixed(1)}°，拖曳距 ${t} mm。`;
$('dfpre').textContent=n('fp').toFixed(2);$('dflsc').textContent=n('flsc');$('dfk1').textContent=n('fk1');$('dfk2').textContent=n('fk2');$('drpre').textContent=n('rp').toFixed(1);$('drlsc').textContent=n('rlsc');$('dk1').textContent=n('rk1');$('dk2').textContent=n('rk2');$('dangle').textContent=ang.toFixed(1)+'°';$('dtrail').textContent=t+' mm';
$('ga').textContent=ang.toFixed(1)+'°';$('gt').textContent=t+' mm';$('gw').textContent=n('wheelbase')+' mm';$('gtires').textContent=$('frontTire').value+' / '+$('rearTire').value}
document.addEventListener('input',e=>{if(e.target.matches('input,select'))calc()});
$('save').onclick=()=>{let d={};document.querySelectorAll('input,select').forEach(x=>d[x.id]=x.value);localStorage.setItem('nsp422',JSON.stringify(d));alert('已保存，本机离线可恢复。')};
function hist(){return JSON.parse(localStorage.getItem('nsp422h')||'[]')}
function chart(id,arr){let c=$(id),ctx=c.getContext('2d'),W=c.clientWidth,H=c.clientHeight;c.width=W*devicePixelRatio;c.height=H*devicePixelRatio;ctx.scale(devicePixelRatio,devicePixelRatio);ctx.clearRect(0,0,W,H);ctx.strokeStyle='#caff00';ctx.lineWidth=2;if(!arr.length){ctx.fillStyle='#899391';ctx.fillText('暂无记录',20,H/2);return}let min=Math.min(...arr),max=Math.max(...arr),r=max-min||1;ctx.beginPath();arr.forEach((v,i)=>{let x=arr.length===1?W/2:i*(W-20)/(arr.length-1)+10,y=H-15-(v-min)/r*(H-35);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}
function render(){let h=hist();chart('chart1',h.map(x=>x.fp));chart('chart2',h.map(x=>x.rp));chart('chart3',h.map(x=>x.score));$('list').innerHTML=h.slice().reverse().map(x=>`<div class="item">${x.time} · 前 K1/K2 ${x.fk1}/${x.fk2} · 后 K1/K2 ${x.rk1}/${x.rk2} · 前叉倾角 ${x.angle}° · Trail ${x.trail} mm · Score ${x.score}</div>`).join('')}
$('record').onclick=()=>{let h=hist();h.push({time:new Date().toLocaleString('zh-CN'),fp:n('fp'),rp:n('rp'),fk1:n('fk1'),fk2:n('fk2'),rk1:n('rk1'),rk2:n('rk2'),angle:n('headAngle'),trail:n('trail'),score:n('score')||+$('score').textContent});localStorage.setItem('nsp422h',JSON.stringify(h.slice(-100)));render()};
$('clear').onclick=()=>{localStorage.removeItem('nsp422h');render()};
function net(){let x=$('net');x.textContent=navigator.onLine?'● 在线':'● 离线模式'}window.ononline=net;window.onoffline=net;
let saved=JSON.parse(localStorage.getItem('nsp422')||'{}');Object.entries(saved).forEach(([k,v])=>{$(k)&&($(k).value=v)});net();model($('model').value||'trail');calc();render();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');